### ISSUE TITLE
Would you please update the chipset to the newer one (like SLB9665VQ20

### ISSUE THREAD

**Issue by GeorgeQii** [jeffqchen/diy_asus_tpm-m_r2.0_module#1]

**Comment by GeorgeQii** [comment]
Because the SLB9665TT20 is out of date on AliExpress, my order has been delayed several weeks.

**Comment by jeffqchen** [comment]
Sorry to hear that but I'm not planning to update this design. I just checked eBay and it seems there are still plenty available. So it's unlikely that they are running out anytime soon.
